# ======== 본문 전체 제공 ========
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/politics.xml"
  category: "정치"
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/international.xml"
  category: "국제"
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/economy.xml"
  category: "경제"
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/bank.xml"
  category: "경제"
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/industry.xml"
  category: "경제"
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/society.xml"
  category: "사회"
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/health.xml"
  category: "IT과학"
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/met.xml"
  category: "사회"
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/country.xml"
  category: "사회"
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/sports.xml"
  category: "스포츠"
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/entertain.xml"
  category: "연예"
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/culture.xml"
  category: "문화"
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/square.xml"
  category: "기타"
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/photo.xml"
  category: "기타"
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/newsiseyes.xml"
  category: "기타"

- source: "연합뉴스TV"
  url: "http://www.yonhapnewstv.co.kr/category/news/politics/feed/"
  category: "정치"
- source: "연합뉴스TV"
  url: "http://www.yonhapnewstv.co.kr/category/news/economy/feed/"
  category: "경제"
- source: "연합뉴스TV"
  url: "http://www.yonhapnewstv.co.kr/category/news/society/feed/"
  category: "사회"
- source: "연합뉴스TV"
  url: "http://www.yonhapnewstv.co.kr/category/news/local/feed/"
  category: "사회"
- source: "연합뉴스TV"
  url: "http://www.yonhapnewstv.co.kr/category/news/international/feed/"
  category: "국제"
- source: "연합뉴스TV"
  url: "http://www.yonhapnewstv.co.kr/category/news/culture/feed/"
  category: "문화"
- source: "연합뉴스TV"
  url: "http://www.yonhapnewstv.co.kr/category/news/sports/feed/"
  category: "스포츠"
- source: "연합뉴스TV"
  url: "http://www.yonhapnewstv.co.kr/category/news/weather/feed/"
  category: "사회"

- source: "국민일보"
  url: "https://www.kmib.co.kr/rss/data/kmibPolRss.xml"
  category: "정치"
- source: "국민일보"
  url: "https://www.kmib.co.kr/rss/data/kmibEcoRss.xml"
  category: "경제"
- source: "국민일보"
  url: "https://www.kmib.co.kr/rss/data/kmibSocRss.xml"
  category: "사회"
- source: "국민일보"
  url: "https://www.kmib.co.kr/rss/data/kmibIntRss.xml"
  category: "국제"
- source: "국민일보"
  url: "https://www.kmib.co.kr/rss/data/kmibEntRss.xml"
  category: "연예"
- source: "국민일보"
  url: "https://www.kmib.co.kr/rss/data/kmibSpoRss.xml"
  category: "스포츠"
- source: "국민일보"
  url: "https://www.kmib.co.kr/rss/data/kmibGolfRss.xml"
  category: "라이프"
- source: "국민일보"
  url: "https://www.kmib.co.kr/rss/data/kmibLifeRss.xml"
  category: "라이프"
- source: "국민일보"
  url: "https://www.kmib.co.kr/rss/data/kmibTraRss.xml"
  category: "라이프"

- source: "서울신문"
  url: "https://www.seoul.co.kr/xml/rss/rss_politics.xml"
  category: "정치"
- source: "서울신문"
  url: "https://www.seoul.co.kr/xml/rss/rss_society.xml"
  category: "사회"
- source: "서울신문"
  url: "https://www.seoul.co.kr/xml/rss/rss_economy.xml"
  category: "경제"
- source: "서울신문"
  url: "https://www.seoul.co.kr/xml/rss/rss_international.xml"
  category: "국제"
- source: "서울신문"
  url: "https://www.seoul.co.kr/xml/rss/rss_life.xml"
  category: "문화"
- source: "서울신문"
  url: "https://www.seoul.co.kr/xml/rss/rss_sports.xml"
  category: "스포츠"
- source: "서울신문"
  url: "https://www.seoul.co.kr/xml/rss/rss_entertainment.xml"
  category: "연예"

- source: "천지일보"
  url: "https://cdn.newscj.com/rss/gns_S1N1.xml"
  category: "정치"
- source: "천지일보"
  url: "https://cdn.newscj.com/rss/gns_S1N2.xml"
  category: "경제"
- source: "천지일보"
  url: "https://cdn.newscj.com/rss/gns_S1N3.xml"
  category: "사회"
- source: "천지일보"
  url: "https://cdn.newscj.com/rss/gns_S1N6.xml"
  category: "문화"
- source: "천지일보"
  url: "https://cdn.newscj.com/rss/gns_S1N14.xml"
  category: "스포츠"
- source: "천지일보"
  url: "https://cdn.newscj.com/rss/gns_S1N15.xml"
  category: "연예"
- source: "천지일보"
  url: "https://cdn.newscj.com/rss/gns_S1N4.xml"
  category: "국제"
- source: "천지일보"
  url: "https://cdn.newscj.com/rss/gns_S1N5.xml"
  category: "기타"
- source: "천지일보"
  url: "https://cdn.newscj.com/rss/gns_S1N16.xml"
  category: "라이프"

- source: "국제신문"
  url: "http://www.kookje.co.kr/news2011/rss/newslist01.xml"
  category: "정치"
- source: "국제신문"
  url: "http://www.kookje.co.kr/news2011/rss/newslist02.xml"
  category: "경제"
- source: "국제신문"
  url: "http://www.kookje.co.kr/news2011/rss/newslist03.xml"
  category: "사회"
- source: "국제신문"
  url: "http://www.kookje.co.kr/news2011/rss/newslist04.xml"
  category: "국제"
- source: "국제신문"
  url: "http://www.kookje.co.kr/news2011/rss/newslist05.xml"
  category: "문화"
- source: "국제신문"
  url: "http://www.kookje.co.kr/news2011/rss/newslist06.xml"
  category: "스포츠"
- source: "국제신문"
  url: "http://www.kookje.co.kr/news2011/rss/newslist08.xml"
  category: "IT과학"
- source: "국제신문"
  url: "http://www.kookje.co.kr/news2011/rss/newslist16.xml"
  category: "기타"
- source: "국제신문"
  url: "http://www.kookje.co.kr/news2011/rss/newslist17.xml"
  category: "기타"

# ======== 본문 일부 제공 ========
- source: "연합뉴스"
  url: "https://www.yna.co.kr/rss/politics.xml"
  category: "정치"
- source: "연합뉴스"
  url: "https://www.yna.co.kr/rss/economy.xml"
  category: "경제"
- source: "연합뉴스"
  url: "https://www.yna.co.kr/rss/industry.xml"
  category: "경제"
- source: "연합뉴스"
  url: "https://www.yna.co.kr/rss/society.xml"
  category: "사회"
- source: "연합뉴스"
  url: "https://www.yna.co.kr/rss/international.xml"
  category: "국제"
- source: "연합뉴스"
  url: "https://www.yna.co.kr/rss/culture.xml"
  category: "문화"
- source: "연합뉴스"
  url: "https://www.yna.co.kr/rss/health.xml"
  category: "라이프"
- source: "연합뉴스"
  url: "https://www.yna.co.kr/rss/entertainment.xml"
  category: "연예"
- source: "연합뉴스"
  url: "https://www.yna.co.kr/rss/sports.xml"
  category: "스포츠"

- source: "경향신문"
  url: "https://www.khan.co.kr/rss/rssdata/politic_news.xml"
  category: "정치"
- source: "경향신문"
  url: "https://www.khan.co.kr/rss/rssdata/economy_news.xml"
  category: "경제"
- source: "경향신문"
  url: "https://www.khan.co.kr/rss/rssdata/society_news.xml"
  category: "사회"
- source: "경향신문"
  url: "https://www.khan.co.kr/rss/rssdata/kh_world.xml"
  category: "국제"
- source: "경향신문"
  url: "https://www.khan.co.kr/rss/rssdata/culture_news.xml"
  category: "문화"
- source: "경향신문"
  url: "https://www.khan.co.kr/rss/rssdata/kh_sports.xml"
  category: "스포츠"
- source: "경향신문"
  url: "https://www.khan.co.kr/rss/rssdata/science_news.xml"
  category: "IT과학"
- source: "경향신문"
  url: "https://www.khan.co.kr/rss/rssdata/life_news.xml"
  category: "라이프"

- source: "뉴스핌"
  url: "http://rss.newspim.com/news/category/101"
  category: "정치"
- source: "뉴스핌"
  url: "http://rss.newspim.com/news/category/103"
  category: "경제"
- source: "뉴스핌"
  url: "http://rss.newspim.com/news/category/102"
  category: "사회"
- source: "뉴스핌"
  url: "http://rss.newspim.com/news/category/107"
  category: "국제"
- source: "뉴스핌"
  url: "http://rss.newspim.com/news/category/106"
  category: "경제"
- source: "뉴스핌"
  url: "http://rss.newspim.com/news/category/105"
  category: "경제"
- source: "뉴스핌"
  url: "http://rss.newspim.com/news/category/112"
  category: "라이프"
- source: "뉴스핌"
  url: "http://rss.newspim.com/news/category/110"
  category: "연예"
- source: "뉴스핌"
  url: "http://rss.newspim.com/news/category/111"
  category: "스포츠"

- source: "동아일보"
  url: "https://rss.donga.com/politics.xml"
  category: "정치"
- source: "동아일보"
  url: "https://rss.donga.com/national.xml"
  category: "사회"
- source: "동아일보"
  url: "https://rss.donga.com/economy.xml"
  category: "경제"
- source: "동아일보"
  url: "https://rss.donga.com/international.xml"
  category: "국제"
- source: "동아일보"
  url: "https://rss.donga.com/science.xml"
  category: "IT과학"
- source: "동아일보"
  url: "https://rss.donga.com/culture.xml"
  category: "문화"
- source: "동아일보"
  url: "https://rss.donga.com/sports.xml"
  category: "스포츠"
- source: "동아일보"
  url: "https://rss.donga.com/health.xml"
  category: "라이프"

- source: "조선일보"
  url: "https://www.chosun.com/arc/outboundfeeds/rss/category/politics/?outputType=xml"
  category: "정치"
- source: "조선일보"
  url: "https://www.chosun.com/arc/outboundfeeds/rss/category/economy/?outputType=xml"
  category: "경제"
- source: "조선일보"
  url: "https://www.chosun.com/arc/outboundfeeds/rss/category/national/?outputType=xml"
  category: "사회"
- source: "조선일보"
  category: "국제"
  url: "https://www.chosun.com/arc/outboundfeeds/rss/category/international/?outputType=xml"
- source: "조선일보"
  url: "https://www.chosun.com/arc/outboundfeeds/rss/category/culture-life/?outputType=xml"
  category: "라이프"
- source: "조선일보"
  url: "https://www.chosun.com/arc/outboundfeeds/rss/category/sports/?outputType=xml"
  category: "스포츠"
- source: "조선일보"
  url: "https://www.chosun.com/arc/outboundfeeds/rss/category/entertainments/?outputType=xml"
  category: "연예"

- source: "미디어오늘"
  url: "https://www.mediatoday.co.kr/rss/S1N2.xml"
  category: "정치"
- source: "미디어오늘"
  url: "https://www.mediatoday.co.kr/rss/S1N3.xml"
  category: "경제"
- source: "미디어오늘"
  url: "https://www.mediatoday.co.kr/rss/S1N4.xml"
  category: "사회"
- source: "미디어오늘"
  url: "https://www.mediatoday.co.kr/rss/S1N5.xml"
  category: "라이프"
- source: "미디어오늘"
  url: "https://www.mediatoday.co.kr/rss/S1N6.xml"
  category: "국제"
- source: "미디어오늘"
  url: "https://www.mediatoday.co.kr/rss/S1N7.xml"
  category: "IT과학"

- source: "세계일보"
  url: "https://www.segye.com/Articles/RSSList/segye_politic.xml"
  category: "정치"
- source: "세계일보"
  url: "https://www.segye.com/Articles/RSSList/segye_economy.xml"
  category: "경제"
- source: "세계일보"
  url: "https://www.segye.com/Articles/RSSList/segye_society.xml"
  category: "사회"
- source: "세계일보"
  url: "https://www.segye.com/Articles/RSSList/segye_international.xml"
  category: "국제"
- source: "세계일보"
  url: "https://www.segye.com/Articles/RSSList/segye_culture.xml"
  category: "문화"
- source: "세계일보"
  url: "https://www.segye.com/Articles/RSSList/segye_entertainment.xml"
  category: "연예"
- source: "세계일보"
  url: "https://www.segye.com/Articles/RSSList/segye_sports.xml"
  category: "스포츠"

- source: "시사저널"
  url: "http://www.sisajournal.com/rss/S1N58.xml"
  category: "정치"
- source: "시사저널"
  url: "http://www.sisajournal.com/rss/S1N47.xml"
  category: "사회"
- source: "시사저널"
  url: "http://www.sisajournal.com/rss/S1N54.xml"
  category: "경제"
- source: "시사저널"
  url: "http://www.sisajournal.com/rss/S1N56.xml"
  category: "라이프"
- source: "시사저널"
  url: "http://www.sisajournal.com/rss/S1N59.xml"
  category: "국제"

- source: "프레시안"
  url: "https://www.pressian.com/api/v3/site/rss/section/66"
  category: "정치"
- source: "프레시안"
  url: "https://www.pressian.com/api/v3/site/rss/section/67"
  category: "경제"
- source: "프레시안"
  url: "https://www.pressian.com/api/v3/site/rss/section/68"
  category: "사회"
- source: "프레시안"
  url: "https://www.pressian.com/api/v3/site/rss/section/69"
  category: "문화"
- source: "프레시안"
  url: "https://www.pressian.com/api/v3/site/rss/section/70"
  category: "스포츠"
- source: "프레시안"
  url: "https://www.pressian.com/api/v3/site/rss/section/65"
  category: "국제"

- source: "뉴스토마토"
  url: "https://www.newstomato.com/rss/?cate=11"
  category: "정치"
- source: "뉴스토마토"
  url: "https://www.newstomato.com/rss/?cate=13"
  category: "경제"
- source: "뉴스토마토"
  url: "https://www.newstomato.com/rss/?cate=14"
  category: "경제"
- source: "뉴스토마토"
  url: "https://www.newstomato.com/rss/?cate=15"
  category: "IT과학"

- source: "매일경제"
  url: "https://www.mk.co.kr/rss/30200030/"
  category: "정치"
- source: "매일경제"
  url: "https://www.mk.co.kr/rss/30100041/"
  category: "경제"
- source: "매일경제"
  url: "https://www.mk.co.kr/rss/50400012/"
  category: "사회"
- source: "매일경제"
  url: "https://www.mk.co.kr/rss/30300018/"
  category: "국제"
- source: "매일경제"
  url: "https://www.mk.co.kr/rss/30000023/"
  category: "문화"
- source: "매일경제"
  url: "https://www.mk.co.kr/rss/71000001/"
  category: "스포츠"

- source: "파이낸셜뉴스"
  url: "https://www.fnnews.com/rss/r20/fn_realnews_all.xml"
  category: "정치"
- source: "파이낸셜뉴스"
  url: "https://www.fnnews.com/rss/r20/fn_realnews_international.xml"
  category: "국제"
- source: "파이낸셜뉴스"
  url: "https://www.fnnews.com/rss/r20/fn_realnews_society.xml"
  category: "사회"
- source: "파이낸셜뉴스"
  url: "https://www.fnnews.com/rss/r20/fn_realnews_economy.xml"
  category: "경제"
- source: "파이낸셜뉴스"
  url: "https://www.fnnews.com/rss/r20/fn_realnews_finance.xml"
  category: "경제"
- source: "파이낸셜뉴스"
  url: "https://www.fnnews.com/rss/r20/fn_realnews_industry.xml"
  category: "경제"
- source: "파이낸셜뉴스"
  url: "https://www.fnnews.com/rss/r20/fn_realnews_it.xml"
  category: "IT과학"
- source: "파이낸셜뉴스"
  url: "https://www.fnnews.com/rss/r20/fn_realnews_medical.xml"
  category: "라이프"
- source: "파이낸셜뉴스"
  url: "https://www.fnnews.com/rss/r20/fn_realnews_culture.xml"
  category: "문화"
