- source: "뉴시스"
  url: "https://www.newsis.com/RSS/politics.xml"
  category: "정치"
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/international.xml"
  category: "국제"
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/economy.xml"
  category: "경제"
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/bank.xml"
  category: "경제"
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/industry.xml"
  category: "경제"
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/society.xml"
  category: "사회"
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/health.xml"
  category: "IT/과학"
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/met.xml"
  category: "사회"
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/country.xml"
  category: "사회"
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/sports.xml"
  category: "스포츠"
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/entertain.xml"
  category: "연예"
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/culture.xml"
  category: "문화"
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/square.xml"
  category: "기타"
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/photo.xml"
  category: "기타"
- source: "뉴시스"
  url: "https://www.newsis.com/RSS/newsiseyes.xml"
  category: "기타"

- source: "연합뉴스TV"
  url: "http://www.yonhapnewstv.co.kr/category/news/politics/feed/"
  category: "정치"
- source: "연합뉴스TV"
  url: "http://www.yonhapnewstv.co.kr/category/news/economy/feed/"
  category: "경제"
- source: "연합뉴스TV"
  url: "http://www.yonhapnewstv.co.kr/category/news/society/feed/"
  category: "사회"
- source: "연합뉴스TV"
  url: "http://www.yonhapnewstv.co.kr/category/news/local/feed/"
  category: "사회"
- source: "연합뉴스TV"
  url: "http://www.yonhapnewstv.co.kr/category/news/international/feed/"
  category: "국제"
- source: "연합뉴스TV"
  url: "http://www.yonhapnewstv.co.kr/category/news/culture/feed/"
  category: "문화"
- source: "연합뉴스TV"
  url: "http://www.yonhapnewstv.co.kr/category/news/sports/feed/"
  category: "스포츠"
- source: "연합뉴스TV"
  url: "http://www.yonhapnewstv.co.kr/category/news/weather/feed/"
  category: "사회"

- source: "국민일보"
  url: "https://www.kmib.co.kr/rss/data/kmibPolRss.xml"
  category: "정치"
- source: "국민일보"
  url: "https://www.kmib.co.kr/rss/data/kmibEcoRss.xml"
  category: "경제"
- source: "국민일보"
  url: "https://www.kmib.co.kr/rss/data/kmibSocRss.xml"
  category: "사회"
- source: "국민일보"
  url: "https://www.kmib.co.kr/rss/data/kmibIntRss.xml"
  category: "국제"
- source: "국민일보"
  url: "https://www.kmib.co.kr/rss/data/kmibEntRss.xml"
  category: "연예"
- source: "국민일보"
  url: "https://www.kmib.co.kr/rss/data/kmibSpoRss.xml"
  category: "스포츠"
- source: "국민일보"
  url: "https://www.kmib.co.kr/rss/data/kmibGolfRss.xml"
  category: "라이프"
- source: "국민일보"
  url: "https://www.kmib.co.kr/rss/data/kmibLifeRss.xml"
  category: "라이프"
- source: "국민일보"
  url: "https://www.kmib.co.kr/rss/data/kmibTraRss.xml"
  category: "라이프"

- source: "서울신문"
  url: "https://www.seoul.co.kr/xml/rss/rss_politics.xml"
  category: "정치"
- source: "서울신문"
  url: "https://www.seoul.co.kr/xml/rss/rss_society.xml"
  category: "사회"
- source: "서울신문"
  url: "https://www.seoul.co.kr/xml/rss/rss_economy.xml"
  category: "경제"
- source: "서울신문"
  url: "https://www.seoul.co.kr/xml/rss/rss_international.xml"
  category: "국제"
- source: "서울신문"
  url: "https://www.seoul.co.kr/xml/rss/rss_life.xml"
  category: "문화"
- source: "서울신문"
  url: "https://www.seoul.co.kr/xml/rss/rss_sports.xml"
  category: "스포츠"
- source: "서울신문"
  url: "https://www.seoul.co.kr/xml/rss/rss_entertainment.xml"
  category: "연예"

- source: "천지일보"
  url: "https://cdn.newscj.com/rss/gns_S1N1.xml"
  category: "정치"
- source: "천지일보"
  url: "https://cdn.newscj.com/rss/gns_S1N2.xml"
  category: "경제"
- source: "천지일보"
  url: "https://cdn.newscj.com/rss/gns_S1N3.xml"
  category: "사회"
- source: "천지일보"
  url: "https://cdn.newscj.com/rss/gns_S1N6.xml"
  category: "문화"
- source: "천지일보"
  url: "https://cdn.newscj.com/rss/gns_S1N14.xml"
  category: "스포츠"
- source: "천지일보"
  url: "https://cdn.newscj.com/rss/gns_S1N15.xml"
  category: "연예"
- source: "천지일보"
  url: "https://cdn.newscj.com/rss/gns_S1N4.xml"
  category: "국제"
- source: "천지일보"
  url: "https://cdn.newscj.com/rss/gns_S1N5.xml"
  category: "기타"
- source: "천지일보"
  url: "https://cdn.newscj.com/rss/gns_S1N16.xml"
  category: "IT/과학"

- source: "아시아뉴스통신"
  url: "https://www.anewsa.com/asianews_rss.php"
  category: "전체"

- source: "국제신문"
  url: "http://www.kookje.co.kr/news2011/rss/newslist01.xml"
  category: "정치"
- source: "국제신문"
  url: "http://www.kookje.co.kr/news2011/rss/newslist02.xml"
  category: "경제"
- source: "국제신문"
  url: "http://www.kookje.co.kr/news2011/rss/newslist03.xml"
  category: "사회"
- source: "국제신문"
  url: "http://www.kookje.co.kr/news2011/rss/newslist04.xml"
  category: "국제"
- source: "국제신문"
  url: "http://www.kookje.co.kr/news2011/rss/newslist05.xml"
  category: "문화"
- source: "국제신문"
  url: "http://www.kookje.co.kr/news2011/rss/newslist06.xml"
  category: "스포츠"
- source: "국제신문"
  url: "http://www.kookje.co.kr/news2011/rss/newslist07.xml"
  category: "라이프"
- source: "국제신문"
  url: "http://www.kookje.co.kr/news2011/rss/newslist08.xml"
  category: "IT/과학"
- source: "국제신문"
  url: "http://www.kookje.co.kr/news2011/rss/newslist16.xml"
  category: "기타"
- source: "국제신문"
  url: "http://www.kookje.co.kr/news2011/rss/newslist17.xml"
  category: "기타"